let datas = [
    {
        location: "kolkata",
        address: "newtown,kolkata",
        price: "1500/month",
        image: require(`./media/home1.jpeg`),
        beds: 2,
        bathroom: 1,
        area: "3x7m2",
        property__type: "house",
        date: "2023-01-01",
    },

    {
        location: "kolkata",
        address: "sealdaha station, kolkata",
        price: "1200/month",
        image: require(`./media/house3.jpg`),
        beds: 2,
        bathroom: 1,
        area: "3x7m2",
        property__type: "house",
        date: "2023-01-01",
    },
    {
        location: "kolkata",
        address: "salt lake, kolkata",
        price: "2200/month",
        image: require(`./media/house2.jpg`),
        beds: 4,
        bathroom: 2,
        area: "3x7m2",
        property__type: "house",
        date: "2023-01-01",
    },
    {
        location: "jalpaiguri",
        address: "near jalpaiguri colledge , jalpaiguri ",
        price: "1300/month",
        image: require(`./media/home1.jpeg`),
        beds: 2,
        bathroom: 1,
        area: "4x7m2",
        property__type: "house",
        date: "2023-05-08",
    },
    {
        location: "murshidabad",
        address: "bhagwangola, murshidabad,742148",
        price: "1000/month",
        image: require(`./media/home1.jpeg`),
        beds: 2,
        bathroom: 1,
        area: "5x7m2",
        property__type: "house",
        date: "2023-07-08",
    },

    {
        location: "england",
        price: "3000/month",
        image: require(`./media/home1.jpeg`),
        beds: 4,
        bathroom: 2,
        area: "10x7m2",
        property__type: "house",
        date: "2023-09-15",
    },
    {
        location: "new york, usa",
        address: "lake-i, new york - usa",
        price: "4000/month",
        image: require(`./media/home1.jpeg`),
        beds: 5,
        bathroom: 2,
        area: "12x7m2",
        property__type: "house",
        date: "2023-05-10",
    },
    {
        location: "new york, usa",
        price: "2000/month",
        image: require(`./media/home1.jpeg`),
        beds: 5,
        bathroom: 2,
        area: "12x7m2",
        property__type: "house",
        date: "2023-05-25",
    },
    {
        location: "china",
        price: "3000/month",
        image: require(`./media/banglow2.jpg`),
        beds: 6,
        bathroom: 2,
        area: "18x7m2",
        property__type: "banglow",
        date: "2023-08-08",
    },
    {
        location: "bangalore",
        price: "3000/month",
        image: require(`./media/banglow1.jpg`),
        beds: 6,
        bathroom: 6,
        area: "18x7m2",
        property__type: "banglow",
        date: "2023-05-05",
    },
];

export { datas };
